Add missing `types-requests` import
Fixes:

```
$ make test
[...]
mypy: install_deps> python -I -m pip install mypy
mypy: install_package_deps> python -I -m pip install requests
mypy: install_package> python -I -m pip install --force-reinstall --no-deps /home/runner/work/public-ip/public-ip/.tox/.tmp/package/2/public-ip-0.12.tar.gz
mypy: freeze> python -m pip freeze --all
mypy: certifi==2024.2.2,charset-normalizer==3.3.2,idna==3.6,mypy==1.9.0,mypy-extensions==1.0.0,pip==24.0,public-ip @ file:///home/runner/work/public-ip/public-ip/.tox/.tmp/package/2/public-ip-0.12.tar.gz#sha256=3874f939a89baf28197d8ea8b8958e4f01665bbc0b30df23fc1b4056d944ac85,requests==2.31.0,setuptools==69.1.0,tomli==2.0.1,typing_extensions==4.10.0,urllib3==2.2.1,wheel==0.42.0
mypy: commands[0]> mypy --ignore-missing-imports -p public_ip
src/public_ip/_ip.py:6: error: Library stubs not installed for "requests"  [import-untyped]
src/public_ip/_ip.py:6: note: Hint: "python3 -m pip install types-requests"
src/public_ip/_ip.py:6: note: (or run "mypy --install-types" to install all missing stub packages)
src/public_ip/_ip.py:6: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 2 source files)
mypy: exit 1 (1.26 seconds) /home/runner/work/public-ip/public-ip> mypy --ignore-missing-imports -p public_ip pid=2062
  py39: OK (10.40=setup[9.14]+cmd[1.25] seconds)
  mypy: FAIL code 1 (7.95=setup[6.69]+cmd[1.26] seconds)
  evaluation failed :( (18.66 seconds)
make: *** [Makefile:8: test] Error 255
Error: Process completed with exit code 2.
```